"**/*.txt":
  processors:
    - backup_file
    - record_to_shared
  config:
    backup_dir: demo/backups

"**/rename_me/*.txt":
  processors:
    - rename_file
    - record_to_shared

".":
  pre_processors:
    - set_path_name_dict
  post_processors:
    - persist_history_sqlite
